### ISSUE TITLE
一本好书

### ISSUE THREAD

**Issue by ttkk1024** [gudaoxuri/Microservices-Architecture#1]
一直断断续续的看作者的书，我以前没有任何系统架构方面的经验，感觉本书写的特别的透彻，让我受益匪浅。非常希望作者继续努力，把本书完成。同时恳请作者加上你的捐赠方式，也方便我们做一些捐赠，以表示我们对你劳动的尊重，谢谢

**Comment by gudaoxuri** [comment]
谢谢鼓励，近期的精力放在 https://github.com/gudaoxuri/dew 项目的2.x版本构建上，预计再过1个月可以beta，之后会继续本书的撰写。

实际上word稿件已经包含了spring cloud及vert.x微服务实践的章节，但目前看来微服务的未来会是容器化和service mesh，所以微服务框架及实践我会重写，dew 2.x也正是向这个方向落地的版本。本书也会成为dew体系的一部分。

ps 捐赠不必了，大家的肯定即是最好的回报。
