### ISSUE TITLE
好多图片加载不出来

### ISSUE THREAD

**Issue by davichi11** [gudaoxuri/Microservices-Architecture#2]
单体架构这一章的图片 
soa架构演进这一章的前两张图
剩下的没看到 但估计也无法加载

**Comment by gudaoxuri** [comment]
修正了，貌似github改过规则，之前图片外链要加 `?sanitize=true` 现在不需要了。

目前主要精力在 https://github.com/gudaoxuri/dew 个把月后会继续撰写此书，谢谢关注。

**Comment by zheyvsu** [comment]
> 修正了，貌似github改过规则，之前图片外链要加 `?sanitize=true` 现在不需要了。
> 
> 目前主要精力在 https://github.com/gudaoxuri/dew 个把月后会继续撰写此书，谢谢关注。

期待中此书后续
