### ISSUE TITLE
网站好多图片都不显示

### ISSUE THREAD

**Issue by xuwangye** [gudaoxuri/Microservices-Architecture#6]
大佬，心血不能蒙尘啊，网站好多图片都不显示，能不能解决一下啊！

**Comment by gudaoxuri** [comment]
图片地址为 “raw.githubusercontent.com/**”  ， 翻墙后正常显示 。

**Comment by xuwangye** [comment]
大佬，我试了试翻墙也不行啊！

**Comment by xuwangye** [comment]
大佬我翻强还是看不到图片啊🙏🙏🙏🙏------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年3月22日(星期一) 上午8:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gudaoxuri/Microservices-Architecture] 网站好多图片都不显示 (#6)

**Comment by li7nux** [comment]
> 大佬，我试了试翻墙也不行啊！

打不开的图片链接发出来看看，我这里都是好的。

**Comment by xuwangye** [comment]
https://raw.githubusercontent.com/gudaoxuri/Microservices-Architecture/master/resources/images/monolithic-architecture.png

**Comment by li7nux** [comment]
> https://raw.githubusercontent.com/gudaoxuri/Microservices-Architecture/master/resources/images/monolithic-architecture.png

翻墙就能打开了

**Comment by xuwangye** [comment]
纳尼！不可能啊！我这自己搭建的vpn，完全可以翻墙啊

**Comment by li7nux** [comment]
> 纳尼！不可能啊！我这自己搭建的vpn，完全可以翻墙啊

针对GitHub的域名加一下规则吧，或者你全局翻墙试试能不能看到图片。

**Comment by xuwangye** [comment]
@li7nux 针对GitHub的域名加一下规则吧 是啥意思？貌似全局也没用......

**Comment by li7nux** [comment]
> @li7nux 针对GitHub的域名加一下规则吧 是啥意思？貌似全局也没用......

全局都没用，那是不是你的代理有问题了 🤣

**Comment by xuwangye** [comment]
啊好了好了，在hosts里面加了185.199.111.133 raw.githubusercontent.com
@li7nux 谢啦
