### ISSUE TITLE
近一年读过最好的书

### ISSUE THREAD

**Issue by Jun10ng** [gudaoxuri/Microservices-Architecture#7]
读完前两章，几乎每一段都能解开我心里一个疑惑。

为什么有的项目说是既不是单体应用又不是纯粹的微服务？原来是SOA啊。
为什么架构图要成这个样子？ 原来是要根据多个维度拆分啊。
解开的疑惑太多了。

如果以后这本书出版了，我斗胆推荐一个副标题：“带你了解微服务中的潜规则”
本人毕业不到一年，这本书解答了我工作以来的大多困惑。

向作者敬礼。
这本书不应该只有100颗stat.
请允许我推荐给我的所有朋友。

**Comment by Jun10ng** [comment]
另：
关于SOA的一个疑惑，
如果一个项目使用**单体代码仓库**，仓库内有多个服务代码，在不同实例上部署各自服务的代码。
但是由于使用单体代码仓库，服务发现相当于是硬编码的（因为所有服务的服务名都硬编码在一个配置文件内了)。
这种架构算是微服务还是SOA呢？

**Comment by gudaoxuri** [comment]
> 另：
> 关于SOA的一个疑惑，
> 如果一个项目使用**单体代码仓库**，仓库内有多个服务代码，在不同实例上部署各自服务的代码。
> 但是由于使用单体代码仓库，服务发现相当于是硬编码的（因为所有服务的服务名都硬编码在一个配置文件内了)。
> 这种架构算是微服务还是SOA呢？

抱歉，不是很理解你的意思。

**单体代码仓库** 是指所有代码在一个git/svn仓库内吗？

However，代码仓库与服务形态在不同场景有一定的推荐实现，但两者并没有强制关联。比如 https://github.com/gudaoxuri/dew/tree/master/examples 我这个仓库下有多个Spring服务示例，它们都是独立的微服务，服务的发现可依赖于注册中心（E.g. nacos、k8s）

**Comment by iaiti** [comment]
写得真好，不用烂大街的商城系统，用了作者实际工作中的项目来做对比，才有了最切身最实际的优劣比较。
和自己负责的平台进行了对比，茅塞顿开，感谢大叔。
